<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>brownNote</RootNamespace>
    <AssemblyName>brownNote</AssemblyName>
    <ApplicationIcon>..\.res\icon\icon.ico</ApplicationIcon>
    <Platforms>x64;ARM64</Platforms>
    <PlatformTarget Condition="'$(Platform)' == 'x64'">x64</PlatformTarget>
    <PlatformTarget Condition="'$(Platform)' == 'ARM64' Or '$(Platform)' == 'arm64'">ARM64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Wasapi" Version="3.1.0" />
    <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
    <PackageReference Include="MaterialDesignColors" Version="2.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\.res\icon\icon512.png" Link="Resources\icon512.png" />
    <Content Include="..\.res\wav\*.wav" Link="Sounds\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Always" />
    <Content Include="..\.version\version" Link="Version" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Always" />
  </ItemGroup>
</Project>
